language: go

go:
  - 1.14.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1

script:
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build -0 tts-save -v

  - if [ $BUILD_GOOS == "windows" ]; then golangci-lint run; fi       # run a bunch of code checkers/linters in parallel

env:
  global:
    - GO111MODULE=on
    - BUILD_GOARCH=amd64
  matrix: 
    - BUILD_GOOS=windows
    - BUILD_GOOS=darwin
    - BUILD_GOOS=linux
