language: go

matrix:
  include:
    - go: master
    - go: 1.14.x
      env: LATEST=true
  allow_failures:
    - go: master

before_install:
  - go get github.com/mitchellh/gox

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
  - go mod vendor

script:
  #- go get -t -v ./...
  #- diff -u <(echo -n) <(gofmt -d .)
  #- go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - if [ "${LATEST}" = "true"]; then gox -os="linux darwin windows" -arch="amd64" -output="tts-save.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
  
deploy:
  provider: releases
  cleanup: false
  api_key:
    # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
    secure: "cQKjM/sXL7PML9QvISqWwJfNAO01lZC5AF4gNqN5thU8hn8RNmTEPz8i4wW33YouHgWjdQPpzec4pZMLfIjStvskQR0YapT7z6pFrQIWQpGvNwzXwqTBRlohIo539dLNVtSYUckYf40Zxce1l711aTXgnnHujX18JmgofOn2F7Zhbbf7HkdPTf2lHPcgs9nrV34OvqGCdEKOMBYXgAQRvZbxXqHSzzT/qXRFlfd9weRR7k9RVboJJIjSiF+r4CmhUyPwpbzN5Wfu1AgANq0KWsX1IWbPshBt8M3opOYqjlV+Sk0S6x8zRJTgjyP7xK6uYBFSKzE6gLkVHvYe3FcteCSAfgifimdvm2+SkHfs9GNpTzSahuhXT2Sb+auMQi3yMK/ev/slQ+m7WIQ5zOPh0mISbLgNhWLljIW8hsAxD1tdori+fdXm/5SS86vVItDII3A2C6zVlRgyrJAhhpvwsVhrFCpSajA8D971OSldA8uwK64Hz7O313a/arjhbCGeGiIksa5ogO7Pzeyvd/DzMUpSTZpwy7ZuElzHnvqwZ+pw/mcOabXZjdkY1QEEM/rkJJzXHaRiJ/NLIKG+uGmffncpJUc6W6c3aPhJ6T6MGpzMGZLbRembvdgklG1uh1RNB74YhhMKx5oNZ8h6gQ3RjzFu5SkHw/z8GzUzXbZ6HvE="
  file:
  # The names of the binaries to output, based on the -output template passed to gox.
  - tts-save.windows.amd64.exe
  - tts-save.darwin.amd64
  - tts-save.linux.amd64
  on:
    # What to repository to build
    repo: asphaltbuffet/tts-save
    # Only build binaries for tagged commits
    tags: true
    condition: $LATEST = true

env:
  global:
    - GO111MODULE=on
    - secure: Kihn7E9w73uXn2oNi+Qq7UBpPa+7IIE70PZUjHvDi0duopwWpwOXbbmWYyp5BjrRsnWNxtPiserhJKIlj8wdtELd2Jo5xZlC0f+nrmlkjmZ3G1+aLCGDNq5sygKd0mbtQvnCavqtvBM2VChuZF9rBQcHIg9/GRmU0IqBySuoCVdLNVZuFTDOE8rjiXEsE4vdzdut52hNsW3GYPR3mIkW2+8d2v1VyHaJMOzBMzmD3capw/TqtK7LztOuZaxdhE1l2dmqR1ZAVoRLMhXrk55p67DcqDPBmea4dHKa0SdNUZZjBa72z5nRSLwJe04BzoLgDeMbnDjFu6HC6JjMfzvjIAqayYcgaE/4h8aV9rEnECxoUxcTgMqOWS1ZurChHdyU0/VhLuwCaLilCqIVN6EIF4cMiNSaTY9Cfobix/9Oh8WS4LsicdTGgO/MLTtmtO5bCNafjfK/5NKAi2BSwnHQt167T2KzqD+EPusts8hiWKLt3vh3OWMrTfvIzZTZwUefzUGU0o8zy4C8Ng4vRXXveCPFWVkQRALAfE+5ZBHYa10vC/JTNzlfg9TPHDeuAqNLbrN0iqvc1I6+uY2v8mPM2MzCvtJnLtfP14QZ3RQTN9WBcVTq8mgQEhMfV10rVQfKI5aeGkqcGYL3W7HE7ZuefEGtvkc0poxGXdnh2R07UDI=