language: go

os:
  - linux
  - windows

go:
  - 1.14.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1

script:
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build -0 tts-save -v

  - golangci-lint run       # run a bunch of code checkers/linters in parallel

env:
  global:
    - GO111MODULE=on
    - BUILD_GOARCH=amd64